const { PrismaClient } = require('@prisma/client');

const prisma = new PrismaClient();

const imageMap = {
  "Wireless Mouse": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Wireless_mouse_block.jpg/500px-Wireless_mouse_block.jpg",
  "Mechanical Keyboard": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Mechanical_keyboard_example.jpg/500px-Mechanical_keyboard_example.jpg",
  "USB-C Hub Adapter": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/USB_OTG_Type-C_Adapter_-_A.jpg/500px-USB_OTG_Type-C_Adapter_-_A.jpg",
  "Noise Cancelling Headphones": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Bose_QuietComfort_25_Acoustic_Noise_Cancelling_Headphones_with_Carry_Case.jpg/500px-Bose_QuietComfort_25_Acoustic_Noise_Cancelling_Headphones_with_Carry_Case.jpg",
  "Desk Lamp": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/A_desk_lamp.jpg/500px-A_desk_lamp.jpg",
  "Webcam HD 1080p": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Logitech_Brio_301_webcam_HS3.jpg/500px-Logitech_Brio_301_webcam_HS3.jpg",
  "Ergonomic Office Chair": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Prototype_ergonomic_office_chair%2C_V%26A_London.jpg/500px-Prototype_ergonomic_office_chair%2C_V%26A_London.jpg",
  "Plant Pot Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Copped_Hall_kitchen_walled_garden%2C_plant_pot_stack%2C_Essex%2C_England.jpg/500px-Copped_Hall_kitchen_walled_garden%2C_plant_pot_stack%2C_Essex%2C_England.jpg",
  "Notebook Journal": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Notebook_writing.jpg/500px-Notebook_writing.jpg",
  "Bluetooth Speaker": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/JBL_Flip_3_bluetooth_speaker_%28DSCF2653%29.jpg/500px-JBL_Flip_3_bluetooth_speaker_%28DSCF2653%29.jpg",
  "Fresh Bananas": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Abundant_Fresh_Bananas_Displayed.jpg/500px-Abundant_Fresh_Bananas_Displayed.jpg",
  "Farm Fresh Apples": "https://upload.wikimedia.org/wikipedia/commons/d/d4/Farm-Fresh_apple.png",
  "Baby Spinach": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/RECALLED-Baby_spinach_%2820800465983%29.jpg/500px-RECALLED-Baby_spinach_%2820800465983%29.jpg",
  "Full Cream Milk": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Milk_bottle_and_two_doughnuts.jpg/500px-Milk_bottle_and_two_doughnuts.jpg",
  "Salted Potato Chips": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Zapp%27s_Potato_Chips_-_Salt_%26_Vinegar.jpg/500px-Zapp%27s_Potato_Chips_-_Salt_%26_Vinegar.jpg",
  "Chocolate Chip Cookies": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/6cookies.JPG/500px-6cookies.JPG",
  "Cold Brew Coffee": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Irish_Cream_Cold_Brew_at_Starbucks_-_2021-11-15_-_Sarah_Stierch.jpg/500px-Irish_Cream_Cold_Brew_at_Starbucks_-_2021-11-15_-_Sarah_Stierch.jpg",
  "Gentle Dish Wash": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Dish-soap.jpg/500px-Dish-soap.jpg",
  "Laundry Liquid Fresh": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/HK_SKD_TKO_Po_Yap_Road_%E5%B0%87%E8%BB%8D%E6%BE%B3%E5%BB%A3%E5%A0%B4_Tseung_Kwan_O_Plaza_K-mart_fresh_food_indoor_market_shop_Kai_Bo_Food_Supermarket_Wayway_Laundry_Liquid_plastic_bottle_July_2021_SS2_01.jpg/500px-thumbnail.jpg",
  "Daily Shampoo": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Dove_shampoo_bottle_in_black_background.jpg/500px-Dove_shampoo_bottle_in_black_background.jpg",
  "Classic Wheat Flour": "https://upload.wikimedia.org/wikipedia/commons/1/11/Wheat-flour.jpg",
  "Fresh Oranges": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d9/Fresh_Oranges.jpg/500px-Fresh_Oranges.jpg",
  "Alphonso Mangoes": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/Alphonso_mango.jpg/500px-Alphonso_mango.jpg",
  "Green Grapes": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Green_Grape_3.jpg/500px-Green_Grape_3.jpg",
  "Pomegranate": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Pomegranate_fruit_-_whole_and_piece_with_arils.jpg/500px-Pomegranate_fruit_-_whole_and_piece_with_arils.jpg",
  "Papaya": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Papaya_-_longitudinal_section_close-up_view.jpg/500px-Papaya_-_longitudinal_section_close-up_view.jpg",
  "Watermelon": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Citrullus_lanatus_03.JPG/500px-Citrullus_lanatus_03.JPG",
  "Pineapple": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/AnanasComosusOnPlant.jpg/500px-AnanasComosusOnPlant.jpg",
  "Avocado": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5d/Avocado_with_cross_section_edit.jpg/500px-Avocado_with_cross_section_edit.jpg",
  "Baby Potatoes": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Baby_potato_and_big_potato.jpg/500px-Baby_potato_and_big_potato.jpg",
  "Red Onions": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Red_Onion_on_White.JPG/500px-Red_Onion_on_White.JPG",
  "Tomatoes": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c3/Organic_home-grown_tomatoes_-_unripe_to_ripe.jpg/500px-Organic_home-grown_tomatoes_-_unripe_to_ripe.jpg",
  "Green Capsicum": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Capsicum_baccatum_in_Sa%C3%BAde_flea_market%2C_S%C3%A3o_Paulo%2C_Brazil.jpg/500px-Capsicum_baccatum_in_Sa%C3%BAde_flea_market%2C_S%C3%A3o_Paulo%2C_Brazil.jpg",
  "Broccoli": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Broccoli_and_cross_section_edit.jpg/500px-Broccoli_and_cross_section_edit.jpg",
  "Cauliflower": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Brassica_oleracea_var._botrytis_%28Coliflor%29.jpg/500px-Brassica_oleracea_var._botrytis_%28Coliflor%29.jpg",
  "Cucumber": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/86/Cucumber_in_jaffna.JPG/500px-Cucumber_in_jaffna.JPG",
  "Carrots": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/32/Carrots_of_many_colors.jpg/500px-Carrots_of_many_colors.jpg",
  "Coriander": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/Coriander_Leaves.jpg/500px-Coriander_Leaves.jpg",
  "Mint Leaves": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Mint_leaves_%28Mentha_spicata%29.jpg/500px-Mint_leaves_%28Mentha_spicata%29.jpg",
  "Sweet Corn": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Sweet_corn_2.jpg/500px-Sweet_corn_2.jpg",
  "Lemons": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/Lemon.jpg/500px-Lemon.jpg",
  "Toned Milk": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Bowl_milk_glass.jpg/500px-Bowl_milk_glass.jpg",
  "Low Fat Milk": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b5/72Magnolia_Low_Fat_Milk.jpg/500px-72Magnolia_Low_Fat_Milk.jpg",
  "Paneer Fresh": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Panir_Paneer_Indian_cheese_fresh.jpg/500px-Panir_Paneer_Indian_cheese_fresh.jpg",
  "Salted Butter": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f9/Stick-of-butter-salted.jpg/500px-Stick-of-butter-salted.jpg",
  "Unsalted Butter": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7d/Lurpak_Butter_250g_unsalted_UK_market.jpg/500px-Lurpak_Butter_250g_unsalted_UK_market.jpg",
  "Cheddar Cheese": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/White_cheddar_cheese.jpg/500px-White_cheddar_cheese.jpg",
  "Mozzarella Cheese": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Mozzarella_cheese.jpg/500px-Mozzarella_cheese.jpg",
  "Greek Yogurt": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Yogurt_fruit_bowl.jpg/500px-Yogurt_fruit_bowl.jpg",
  "Plain Curd": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Curd_in_steel_bowl.jpg/500px-Curd_in_steel_bowl.jpg",
  "Strawberry Yogurt": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Strawberry_with_yogurt_%287471571336%29.jpg/500px-Strawberry_with_yogurt_%287471571336%29.jpg",
  "Buttermilk": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Buttermilk-%28right%29-and-Milk-%28left%29.jpg/500px-Buttermilk-%28right%29-and-Milk-%28left%29.jpg",
  "Fresh Cream": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Whipping_cream_%283372596784%29.jpg/500px-Whipping_cream_%283372596784%29.jpg",
  "Coconut Milk": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Coconut_milk_from_can01.JPG/500px-Coconut_milk_from_can01.JPG",
  "Almond Milk": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/de/Home-made_almond_milk%2C_November_2012.jpg/500px-Home-made_almond_milk%2C_November_2012.jpg",
  "Chocolate Milk": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Chocolate_milk.JPG/500px-Chocolate_milk.JPG",
  "Brown Eggs": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Eggs_in_basket_2020_G1.jpg/500px-Eggs_in_basket_2020_G1.jpg",
  "Quail Eggs": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Quail_eggs_%28%D0%9F%D0%B5%D1%80%D0%B5%D0%BF%D0%B5%D0%BB%D0%B8%D0%BD%D1%8B%D0%B5_%D1%8F%D0%B9%D1%86%D0%B0%29.jpg/500px-Quail_eggs_%28%D0%9F%D0%B5%D1%80%D0%B5%D0%BF%D0%B5%D0%BB%D0%B8%D0%BD%D1%8B%D0%B5_%D1%8F%D0%B9%D1%86%D0%B0%29.jpg",
  "Cheese Slices": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0d/White_cheddar_cheese_sliced_CNE.jpg/500px-White_cheddar_cheese_sliced_CNE.jpg",
  "Cottage Cheese": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Cottage_Cheese.jpg/500px-Cottage_Cheese.jpg",
  "Vanilla Yogurt": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Yogurt_from_Turkey.jpg/500px-Yogurt_from_Turkey.jpg",
  "Classic Nachos": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Classic_Nachos_with_Fajita_Chicken.jpg/500px-Classic_Nachos_with_Fajita_Chicken.jpg",
  "Cheese Puffs": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/No_Name_cheese_flavour_twists%2C_Canada%2C_detail_02.jpg/500px-No_Name_cheese_flavour_twists%2C_Canada%2C_detail_02.jpg",
  "Roasted Peanuts": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/36/Roasted_Peanuts_with_shell.jpg/500px-Roasted_Peanuts_with_shell.jpg",
  "Salted Cashews": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/OG_Choc_Sea_Salt_Cashews_Lo_Res.jpg/500px-OG_Choc_Sea_Salt_Cashews_Lo_Res.jpg",
  "Trail Mix": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Planters-Trail-Mix.jpg/500px-Planters-Trail-Mix.jpg",
  "Granola Bars": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Homemade_granola_bars_%289276339927%29.jpg/500px-Homemade_granola_bars_%289276339927%29.jpg",
  "Oat Cookies": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Oatmeal_cookies_on_a_plate.jpg/500px-Oatmeal_cookies_on_a_plate.jpg",
  "Cream Biscuits": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Biscuits_perspective.jpg/500px-Biscuits_perspective.jpg",
  "Butter Crackers": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Saltine-Crackers.JPG/500px-Saltine-Crackers.JPG",
  "Kettle Corn": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Kettle_Corn_BSAF.jpg/500px-Kettle_Corn_BSAF.jpg",
  "Roasted Makhana": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Roasted_Makhana_%28Foxnut%29.jpg/500px-Roasted_Makhana_%28Foxnut%29.jpg",
  "Banana Chips": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Kerala_banana_chips_Upperi_varuthath.jpg/500px-Kerala_banana_chips_Upperi_varuthath.jpg",
  "Peanut Chikki": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/51/Peanut_Chikki_With_Caramel.jpg/500px-Peanut_Chikki_With_Caramel.jpg",
  "Protein Bar": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/49/LUNA_Protein_Mint_Chocolate_Chip_bar_cut_in_half.jpg/500px-LUNA_Protein_Mint_Chocolate_Chip_bar_cut_in_half.jpg",
  "Rice Cakes": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Rice_cakes_with_smoked_snoek_pate.jpg/500px-Rice_cakes_with_smoked_snoek_pate.jpg",
  "Popcorn Butter": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Popcorn_with_butter_and_a_little_salt_-_Massachusetts.jpg/500px-Popcorn_with_butter_and_a_little_salt_-_Massachusetts.jpg",
  "Fruit Gummies": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Shameless_Snacks_gummy_bears.jpg/500px-Shameless_Snacks_gummy_bears.jpg",
  "Mango Juice": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9a/Glass_of_Mango_Juice.jpg/500px-Glass_of_Mango_Juice.jpg",
  "Orange Juice": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/Orange_juice_1_edit1.jpg/500px-Orange_juice_1_edit1.jpg",
  "Apple Juice": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ee/Freshippo_apple_juice.jpg/500px-Freshippo_apple_juice.jpg",
  "Coconut Water": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/56/Coconut_with_it%27s_water.jpg/500px-Coconut_with_it%27s_water.jpg",
  "Mineral Water": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/Water_bottle_11-26-2025.jpg/500px-Water_bottle_11-26-2025.jpg",
  "Green Tea": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d0/Green_Tea_Cup_with_Hollandia_milk.jpg/500px-Green_Tea_Cup_with_Hollandia_milk.jpg",
  "Masala Tea": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d7/Masala_Tea_-_2.jpg/500px-Masala_Tea_-_2.jpg",
  "Instant Coffee": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dc/From_coffee_bean_to_instant_coffee_01.jpg/500px-From_coffee_bean_to_instant_coffee_01.jpg",
  "Iced Tea Peach": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6b/Peach_iced_tea_with_orange_slices.jpg/500px-Peach_iced_tea_with_orange_slices.jpg",
  "Cola Classic": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e8/15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_%28Germany%29.jpg/500px-15-09-26-RalfR-WLC-0098_-_Coca-Cola_glass_bottle_%28Germany%29.jpg",
  "Ginger Ale": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/09/Ginger_ale.jpg/500px-Ginger_ale.jpg",
  "Tonic Water": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Tonic_water_uv.jpg/500px-Tonic_water_uv.jpg",
  "Energy Drink": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/Energy_Drink_Battery_Cans.jpg/500px-Energy_Drink_Battery_Cans.jpg",
  "Sports Drink": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Gatorade_Thirst_Quencher.jpg/500px-Gatorade_Thirst_Quencher.jpg",
  "Lemonade": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3a/Lemonade_and_teacup.jpg/500px-Lemonade_and_teacup.jpg",
  "Berry Smoothie": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Kid_friendly_green_smoothie_in_a_personalized_glass_with_spinach%2C_Greek_yogurt%2C_frozen_blueberries%2C_blackberries_and_strawberries_and_berries%2C_banana_in_a_glass_bowl_on_a_wood_table_%2816225943125%29.jpg/500px-thumbnail.jpg",
  "Mango Lassi": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/Mango_Lassi_and_Butter_Milk_-_Vel_South_Indian_Kitchen_%2B_Bar.jpg/500px-Mango_Lassi_and_Butter_Milk_-_Vel_South_Indian_Kitchen_%2B_Bar.jpg",
  "Vanilla Milkshake": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/aa/Milkshake_and_Vanilla_Cake.jpg/500px-Milkshake_and_Vanilla_Cake.jpg",
  "Hot Chocolate": "https://upload.wikimedia.org/wikipedia/commons/1/14/Hot_chocolate_mug_with_whipped_cream.jpg",
  "Herbal Infusion": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6f/Herbal_Tea_01.jpg/500px-Herbal_Tea_01.jpg",
  "Floor Cleaner Lemon": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Polti_steam_mop_or_portable.jpg/500px-Polti_steam_mop_or_portable.jpg",
  "Glass Cleaner": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/Windex_%2848089717956%29.jpg/500px-Windex_%2848089717956%29.jpg",
  "Bathroom Cleaner": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Badreiniger.jpg/500px-Badreiniger.jpg",
  "Toilet Cleaner": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/ToiletcleanersbyAlofok_%284%29.JPG/500px-ToiletcleanersbyAlofok_%284%29.JPG",
  "Kitchen Degreaser": "https://upload.wikimedia.org/wikipedia/commons/f/f5/Foaming_degreaser.JPG",
  "Disinfectant Spray": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Disinfectant_spray_-_geograph.org.uk_-_3570743.jpg/500px-Disinfectant_spray_-_geograph.org.uk_-_3570743.jpg",
  "Multi Surface Cleaner": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b4/Globus_Saarbr%C3%BCcken%2C_all_purpose_cleaner_pic2.JPG/500px-Globus_Saarbr%C3%BCcken%2C_all_purpose_cleaner_pic2.JPG",
  "Fabric Softener": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Globus_Saarbr%C3%BCcken%2C_fabric_softener_pic7.JPG/500px-Globus_Saarbr%C3%BCcken%2C_fabric_softener_pic7.JPG",
  "Washing Powder": "https://upload.wikimedia.org/wikipedia/commons/c/c3/Gold_Dust_Washing_Soap_box.jpg",
  "Dishwasher Tablets": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ad/Dishwasher_Tablets_White_Machine_Edited_2020_%2849913643821%29.jpg/500px-Dishwasher_Tablets_White_Machine_Edited_2020_%2849913643821%29.jpg",
  "Sponge Scrubbers": "https://upload.wikimedia.org/wikipedia/commons/6/6b/Broom%2C_sponge_and_towel.jpg",
  "Microfiber Cloths": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cd/Microfiber_cloth.jpg/500px-Microfiber_cloth.jpg",
  "Garbage Bags": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3c/Garbage_bags_outside_in_neighborhood_at_twilight.jpg/500px-Garbage_bags_outside_in_neighborhood_at_twilight.jpg",
  "Kitchen Towels": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c3/Home_kitchen_details_June_2023_-_corner_by_kitchen_sink_with_filtered_water_and_towels.jpg/500px-Home_kitchen_details_June_2023_-_corner_by_kitchen_sink_with_filtered_water_and_towels.jpg",
  "Air Freshener": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Air_Wick_automatic_air_freshener-5060.jpg/500px-Air_Wick_automatic_air_freshener-5060.jpg",
  "Mosquito Repellent": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Mosquito_repellent_incense_stick_and_incense_stick_base.jpg/500px-Mosquito_repellent_incense_stick_and_incense_stick_base.jpg",
  "Toilet Freshener": "https://upload.wikimedia.org/wikipedia/commons/0/0b/Toilet_Rim_Block.jpg",
  "Drain Opener": "https://upload.wikimedia.org/wikipedia/commons/4/41/Acidic_drain_opener.jpg",
  "Rubber Gloves": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/Butyl_rubber_gloves.JPG/500px-Butyl_rubber_gloves.JPG",
  "Storage Bags": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Two_zipper_storage_bags_A.jpg/500px-Two_zipper_storage_bags_A.jpg",
  "Vitamin C Serum": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Woman_applying_serum_on_her_face_closeup.jpg/500px-Woman_applying_serum_on_her_face_closeup.jpg",
  "Sunscreen SPF 50": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/LRP_sunscreen_bottle.jpg/500px-LRP_sunscreen_bottle.jpg",
  "Lip Balm": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/Various_colorful_lip_balm_sticks_%2840821280864%29.jpg/500px-Various_colorful_lip_balm_sticks_%2840821280864%29.jpg",
  "Body Lotion": "https://upload.wikimedia.org/wikipedia/commons/0/08/Absolute_Tulip_Lotion_-_%287028027789%29.jpg",
  "Hand Wash": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Use_of_a_touchless_hand_washing_tap_and_solid_bar_soap_dispenser.jpg/500px-Use_of_a_touchless_hand_washing_tap_and_solid_bar_soap_dispenser.jpg",
  "Body Wash": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/Kenvue_shower_gel_with_a_complicated_story_to_tell.jpg/500px-Kenvue_shower_gel_with_a_complicated_story_to_tell.jpg",
  "Conditioner": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b6/Hair_shampoos%2C_conditioners_and_other_hair_care_products_in_liter_bottles_for_use_in_hair_salon.jpg/500px-Hair_shampoos%2C_conditioners_and_other_hair_care_products_in_liter_bottles_for_use_in_hair_salon.jpg",
  "Hair Oil": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/72/Bottle%2C_hair_oil_%28AM_1965.78.847-5%29.jpg/500px-Bottle%2C_hair_oil_%28AM_1965.78.847-5%29.jpg",
  "Toothpaste Fresh Mint": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8c/Vitis_Dentaid_toothpaste_tube%2C_Hillegersberg%2C_Rotterdam_%282021%29_01.jpg/500px-Vitis_Dentaid_toothpaste_tube%2C_Hillegersberg%2C_Rotterdam_%282021%29_01.jpg",
  "Toothbrush Soft": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Curaprox_blue_smart_ultra_soft_toothbrush%2C_Hillegersberg%2C_Rotterdam_%282021%29_05.jpg/500px-Curaprox_blue_smart_ultra_soft_toothbrush%2C_Hillegersberg%2C_Rotterdam_%282021%29_05.jpg",
  "Mouthwash": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/01/Crystal_White_Mouthwash_Shelf.jpg/500px-Crystal_White_Mouthwash_Shelf.jpg",
  "Deodorant Roll On": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/20-06-18-Deoroller_RRK6899.jpg/500px-20-06-18-Deoroller_RRK6899.jpg",
  "Bath Soap": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b2/Soap_from_Bath_and_Body_Works.png/500px-Soap_from_Bath_and_Body_Works.png",
  "Hand Cream": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/71/Woman_applying_cream_to_hand.jpg/500px-Woman_applying_cream_to_hand.jpg",
  "Face Scrub": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/83/Exfoliating_face_scrub.jpg/500px-Exfoliating_face_scrub.jpg",
  "Cotton Buds": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Cotton_swabs_%28or_cotton_buds%29_-in_round_container.jpg/500px-Cotton_swabs_%28or_cotton_buds%29_-in_round_container.jpg",
  "Tissue Box": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/79/A_tissue_box.jpg/500px-A_tissue_box.jpg",
  "Wet Wipes": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Wet_wipes_on_a_shelf.jpg/500px-Wet_wipes_on_a_shelf.jpg",
  "Shaving Foam": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/14/GILLETTE_FOAMY_SHAVING_CREAM_CHINA_VERSION.jpg/500px-GILLETTE_FOAMY_SHAVING_CREAM_CHINA_VERSION.jpg",
  "Toor Dal": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7c/Straucherbsen_%28Toor_Dal%29_in_einem_indischen_Supermarkt.jpeg/500px-Straucherbsen_%28Toor_Dal%29_in_einem_indischen_Supermarkt.jpeg",
  "Moong Dal": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Green_Moong_Dal.jpg/500px-Green_Moong_Dal.jpg",
  "Chana Dal": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7a/Chana_Ko_Dal.jpg/500px-Chana_Ko_Dal.jpg",
  "Rajma Red": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c6/Red_Speckled_Kidney_Beans.jpg/500px-Red_Speckled_Kidney_Beans.jpg",
  "Kabuli Chana": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b6/WHITE_KABULI_CHANA.jpg/500px-WHITE_KABULI_CHANA.jpg",
  "Poha Thick": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Poha.jpg/500px-Poha.jpg",
  "Oats Rolled": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/97/Rolled_oats.jpg/500px-Rolled_oats.jpg",
  "Quinoa": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/Quinoa_closeup.jpg/500px-Quinoa_closeup.jpg",
  "Brown Rice": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Brown_Rice.jpg/500px-Brown_Rice.jpg",
  "Sugar Fine": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Nurse_holding_a_glass_jar_of_white_sugar_cubes_closeup.jpg/500px-Nurse_holding_a_glass_jar_of_white_sugar_cubes_closeup.jpg",
  "Rock Salt": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/96/Halite-rock-salt-inowroclaw-poland.jpg/500px-Halite-rock-salt-inowroclaw-poland.jpg",
  "Black Pepper": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/31/Black_Pepper_%28Piper_nigrum%29_fruits.jpg/500px-Black_Pepper_%28Piper_nigrum%29_fruits.jpg",
  "Turmeric Powder": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Chlorofeel_Spices_Turmeric_Powder_Packet.jpg/500px-Chlorofeel_Spices_Turmeric_Powder_Packet.jpg",
  "Red Chilli Powder": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/Chilli_powder_for_sale.JPG/500px-Chilli_powder_for_sale.JPG",
  "Garam Masala": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0f/Garam_Masala_1.jpg/500px-Garam_Masala_1.jpg",
  "Refined Sunflower Oil": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Bottle_1_liter_Sunflower_refined_oil.jpg/500px-Bottle_1_liter_Sunflower_refined_oil.jpg",
  "Extra Virgin Olive Oil": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Villa_Torrigiani_Extra_virgin_Olive_Oil.jpg/500px-Villa_Torrigiani_Extra_virgin_Olive_Oil.jpg",
  "Peanut Butter": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a8/Peanut-Butter-Jelly-Sandwich.jpg/500px-Peanut-Butter-Jelly-Sandwich.jpg",
  "Tomato Ketchup": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d3/Heinz_Tomato_Ketchup%2C_Canada_%28front%29%2C_2026-02-19.jpg/500px-Heinz_Tomato_Ketchup%2C_Canada_%28front%29%2C_2026-02-19.jpg",
  "Mixed Pickle": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Mixed_Pickles_%289370-72%29.jpg/500px-Mixed_Pickles_%289370-72%29.jpg",
  "Laptop Sleeve": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d6/Laptop_Case_-_texture.jpg/500px-Laptop_Case_-_texture.jpg",
  "Wireless Mouse Pad": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Mouse_on_uPad_%283253884463%29.jpg/500px-Mouse_on_uPad_%283253884463%29.jpg",
  "USB-C Cable": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6c/USB-C_cable_connected_to_a_powerbank.jpg/500px-USB-C_cable_connected_to_a_powerbank.jpg",
  "HDMI Cable": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/HDMI_Cable_1.JPG/500px-HDMI_Cable_1.JPG",
  "Phone Stand": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/DIY_tablet_smartphone_stand_2.jpg/500px-DIY_tablet_smartphone_stand_2.jpg",
  "Laptop Stand": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Laptop_stand.jpg/500px-Laptop_stand.jpg",
  "Cable Organizer": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d9/Cable_Comb%C2%AE_Cable_Organizing_Tool_%28CCB-25%29.jpg/500px-Cable_Comb%C2%AE_Cable_Organizing_Tool_%28CCB-25%29.jpg",
  "Wireless Presenter": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1d/Inateck_WP1002_Wireless_Presenter_%2816778919271%29.jpg/500px-Inateck_WP1002_Wireless_Presenter_%2816778919271%29.jpg",
  "Keyboard Wrist Rest": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fd/Dell_KB522_--_top_with_wrist_rest_detached.jpg/500px-Dell_KB522_--_top_with_wrist_rest_detached.jpg",
  "Desk Mat": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/EFTA00001227_-_Vibrant_turquoise_desk_features_a_black_Apple_iMac_keyboard_mouse_pad_white_telephone_and_framed_photos_set_against_a_modern_living_room_backdrop.jpg/500px-thumbnail.jpg",
  "Webcam Cover": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/00/CGI_webcam_cover%2C_Oude_Pekela_%282020%29_05.jpg/500px-CGI_webcam_cover%2C_Oude_Pekela_%282020%29_05.jpg",
  "Screen Cleaning Kit": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/23/Cleaning_a_camera_LCD_before_applying_a_screen_protector.jpg/500px-Cleaning_a_camera_LCD_before_applying_a_screen_protector.jpg",
  "Bluetooth Adapter": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/Rocketfish_Bluetooth_USB_adapter_HS3.jpg/500px-Rocketfish_Bluetooth_USB_adapter_HS3.jpg",
  "USB Flash Drive": "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/19/2023_Pendrive%27y_Verbatim_Store_%E2%80%98n%E2%80%99_Click_16_GB_%281%29.jpg/500px-2023_Pendrive%27y_Verbatim_Store_%E2%80%98n%E2%80%99_Click_16_GB_%281%29.jpg",
  "Card Reader": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c2/SanDisk_CFexpress_card_reader-oblique_PNr%C2%B00908.jpg/500px-SanDisk_CFexpress_card_reader-oblique_PNr%C2%B00908.jpg",
  "Phone Grip": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/80/Swarovski_crystal_PopSockets_grip_.jpg/500px-Swarovski_crystal_PopSockets_grip_.jpg",
  "Tablet Sleeve": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/ReMarkable_tablet_with_sleeve_and_pen.jpg/500px-ReMarkable_tablet_with_sleeve_and_pen.jpg",
  "Travel Adapter": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Travel_adapter_in_action.jpeg/500px-Travel_adapter_in_action.jpeg",
  "Charging Dock": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/Delock_USB_m.2_NVMe_docking_station-oblique_FS_PNr%C2%B00912.jpg/500px-Delock_USB_m.2_NVMe_docking_station-oblique_FS_PNr%C2%B00912.jpg",
  "Smart Tag": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/SmartTag.JPG/500px-SmartTag.JPG",
  "Smart LED Bulb": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a3/Tapo_smart_LED_bulb_lighting_sample.jpg/500px-Tapo_smart_LED_bulb_lighting_sample.jpg",
  "Wi-Fi Router": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/ASUS_Wi-Fi_ROUTER_TUF_6500.jpg/500px-ASUS_Wi-Fi_ROUTER_TUF_6500.jpg",
  "Smart Plug": "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Smart_plug_adapter_front_view_with_power_button.jpg/500px-Smart_plug_adapter_front_view_with_power_button.jpg",
  "Fitness Band": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/Fitbit_Alta_HR.jpg/500px-Fitbit_Alta_HR.jpg",
  "Smart Watch": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Grey_Smart_Watch.jpg/500px-Grey_Smart_Watch.jpg",
  "Mini Projector": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Sony_Portable_Ultra_Short_Throw_Projector_%2826089157293%29.jpg/500px-Sony_Portable_Ultra_Short_Throw_Projector_%2826089157293%29.jpg",
  "Wireless Earbuds": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4e/Wireless_3.0_Earbuds_Transparent_3.png/500px-Wireless_3.0_Earbuds_Transparent_3.png",
  "Soundbar": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c8/Philips_Soundbar_with_Ambisound_HTS9140_front.jpg/500px-Philips_Soundbar_with_Ambisound_HTS9140_front.jpg",
  "E-Reader": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d5/Kobo_H20_e-reader.jpg/500px-Kobo_H20_e-reader.jpg",
  "Action Camera": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e7/Drift_Ghost_XL_Pro_Action_Camera.jpg/500px-Drift_Ghost_XL_Pro_Action_Camera.jpg",
  "Tripod Stand": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Mini_tripod_and_phone_holder.jpg/500px-Mini_tripod_and_phone_holder.jpg",
  "Electric Kettle": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/2023_Czajnik_elektryczny_N%27OVEEN.jpg/500px-2023_Czajnik_elektryczny_N%27OVEEN.jpg",
  "Air Purifier": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Air_Purifier_%28Levoit_LV-H133%29_%2849317867758%29.jpg/500px-Air_Purifier_%28Levoit_LV-H133%29_%2849317867758%29.jpg",
  "Robot Vacuum": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d4/Robot_Vacuum_2016_%2831606445890%29.jpg/500px-Robot_Vacuum_2016_%2831606445890%29.jpg",
  "Digital Weighing Scale": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Escali_digital_kitchen_scale.jpg/500px-Escali_digital_kitchen_scale.jpg",
  "Power Strip": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/%2820241007%29_APC_power_strip.jpg/500px-%2820241007%29_APC_power_strip.jpg",
  "LED Strip Lights": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/LED_strip_closeup.jpg/500px-LED_strip_closeup.jpg",
  "Table Fan": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/40/Table_fan_FT-1201_II_30_cm_9186.jpg/500px-Table_fan_FT-1201_II_30_cm_9186.jpg",
  "Electric Toothbrush": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/2024_Szczoteczka_do_z%C4%99b%C3%B3w_Oral-B_Pro_3_3000_%282%29.jpg/500px-2024_Szczoteczka_do_z%C4%99b%C3%B3w_Oral-B_Pro_3_3000_%282%29.jpg",
  "Phone Gimbal": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/NEWTON-S2-gimbal-RED-camera-Teradek_lens-motors-and-Angeniuex-lens.jpg/500px-NEWTON-S2-gimbal-RED-camera-Teradek_lens-motors-and-Angeniuex-lens.jpg",
  "Cotton Cushion Set": "https://upload.wikimedia.org/wikipedia/commons/a/a0/Throw_pillows.jpg",
  "Ceramic Dinner Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c3/Dinner_set_%28AM_2017.80.1-9%29.jpg/500px-Dinner_set_%28AM_2017.80.1-9%29.jpg",
  "Glass Tumbler Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/29/Old_Overholt_Rye_Whiskey_bottle_and_tumbler.jpg/500px-Old_Overholt_Rye_Whiskey_bottle_and_tumbler.jpg",
  "Wooden Serving Tray": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8f/Wooden_Tray.jpg/500px-Wooden_Tray.jpg",
  "Bath Towel": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/59/Hotel_Atlantic_in_Hamburg_-_bath_towel.jpg/500px-Hotel_Atlantic_in_Hamburg_-_bath_towel.jpg",
  "Hand Towel Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Tea_towels_%28set_of%29_%28AM_2002.64.1-3%29.jpg/500px-Tea_towels_%28set_of%29_%28AM_2002.64.1-3%29.jpg",
  "Scented Candle": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/Mahogany_teakwood_scented_candle_%28cropped%29.jpg/500px-Mahogany_teakwood_scented_candle_%28cropped%29.jpg",
  "Decorative Vase": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9e/Siervaas_Berlage.jpg/500px-Siervaas_Berlage.jpg",
  "Bamboo Basket": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Craftmen_at_work%2C_bamboo_basket_weaving_and_textile_mobile_sculptures%2C_in_Heuan_Chan_heritage_house%2C_Luang_Prabang%2C_Laos.jpg/500px-Craftmen_at_work%2C_bamboo_basket_weaving_and_textile_mobile_sculptures%2C_in_Heuan_Chan_heritage_house%2C_Luang_Prabang%2C_Laos.jpg",
  "Storage Organizer": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Blue_plastic_storage_organizer_boxes_for_screws.jpg/500px-Blue_plastic_storage_organizer_boxes_for_screws.jpg",
  "Bedside Lamp": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2f/Lamp_with_a_lampshade_illuminated_by_sunlight.jpg/500px-Lamp_with_a_lampshade_illuminated_by_sunlight.jpg",
  "Wall Clock": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a4/Wall_Clock_MET_80840.jpg/500px-Wall_Clock_MET_80840.jpg",
  "Photo Frame": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/Digital_photo_frame_with_picture.jpg/500px-Digital_photo_frame_with_picture.jpg",
  "Coaster Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/89/Parchinkari_white_marble_coaster_set_from_Agra_India.jpg/500px-Parchinkari_white_marble_coaster_set_from_Agra_India.jpg",
  "Kitchen Apron": "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/DFC_4730_A_woman_in_a_colorful_apron_and_headscarf_stands_in_a_small_warmly_lit_kitchen_surrounded_by_cooking_utensils_storage_shelves_and_a_refrigerator_-_a_cozy_everyday_scene_in_Bang_Lamung_Chon_Buri.jpg/500px-thumbnail.jpg",
  "Water Bottle": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Metal_Water_Bottles.jpeg/500px-Metal_Water_Bottles.jpeg",
  "Lunch Box": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/Lunch_box_in_japanese_style_%28in_Macau%29.jpg/500px-Lunch_box_in_japanese_style_%28in_Macau%29.jpg",
  "Curtain Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/EFTA00001121_-_Cozy_bedroom_with_a_blue_wall_floral_headboard_patterned_curtains_and_a_tartan_carpet.jpg/500px-EFTA00001121_-_Cozy_bedroom_with_a_blue_wall_floral_headboard_patterned_curtains_and_a_tartan_carpet.jpg",
  "Door Mat": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Lions_mat_in_Catalan.jpg/500px-Lions_mat_in_Catalan.jpg",
  "Laundry Basket": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0b/2021-07-24_repaired_laundry_basket_01.jpg/500px-2021-07-24_repaired_laundry_basket_01.jpg",
  "Highlighter Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/BIC_Brite_Liner_highlighter%2C_orange.jpg/500px-BIC_Brite_Liner_highlighter%2C_orange.jpg",
  "Sticky Notes": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7f/Sticky_Note_on_a_white_background.jpg/500px-Sticky_Note_on_a_white_background.jpg",
  "A4 Notebook": "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Cuaderno_Cervantes_A4.jpg/500px-Cuaderno_Cervantes_A4.jpg",
  "Drawing Pencils": "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b1/Colouring_pencils.jpg/500px-Colouring_pencils.jpg",
  "Whiteboard Marker": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fe/Whiteboard_marker_and_eraser.jpg/500px-Whiteboard_marker_and_eraser.jpg",
  "Stapler Kit": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/54/Kit_grapadora_t%C3%A8rmica.jpg/500px-Kit_grapadora_t%C3%A8rmica.jpg",
  "Paper Clips": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Paper-clip.jpg/500px-Paper-clip.jpg",
  "File Folder Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Manila_Folders.jpg/500px-Manila_Folders.jpg",
  "Envelope Pack": "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/55/Envelopes_%28Unsplash%29.jpg/500px-Envelopes_%28Unsplash%29.jpg",
  "Correction Tape": "https://upload.wikimedia.org/wikipedia/commons/7/7c/Correction_tape_dispenser.png",
  "Desk Calendar": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/07/Desk_calendar_2022_July_11_-_03-53PM.jpeg/500px-Desk_calendar_2022_July_11_-_03-53PM.jpeg",
  "Scissors": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/76/Pair_of_scissors_with_black_handle%2C_2015-06-07.jpg/500px-Pair_of_scissors_with_black_handle%2C_2015-06-07.jpg",
  "Glue Stick": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/74/FABER-CASTELL_glue_stick.jpg/500px-FABER-CASTELL_glue_stick.jpg",
  "Ruler Set": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/73/Ruler_4scales.jpg/500px-Ruler_4scales.jpg",
  "Sketchbook": "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9d/Sketch-book.jpg/500px-Sketch-book.jpg",
  "Binder Clips": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Binder_clips_arranged_in_a_circle.jpg/500px-Binder_clips_arranged_in_a_circle.jpg",
  "Index Cards": "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e6/Package_of_index_cards-agr.jpg/500px-Package_of_index_cards-agr.jpg",
  "Clipboard": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c0/Wood-clipboard.jpg/500px-Wood-clipboard.jpg",
  "Monitor Stand Riser": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Laptop_and_monitor_on_a_stands.jpg/500px-Laptop_and_monitor_on_a_stands.jpg",
  "Portable Charger 20000mAh": "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Portable_power_bank.jpg/500px-Portable_power_bank.jpg",
  "Farm Eggs 12 Pack": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Egg_cartons_with_chicken_eggs_02.jpg/500px-Egg_cartons_with_chicken_eggs_02.jpg",
  "Sparkling Lime Soda": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Nimbu_Soda_Or_Lemon_Soda.jpg/500px-Nimbu_Soda_Or_Lemon_Soda.jpg",
  "Basmati Rice 5kg": "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Basmati_Rice_India%2C_raw.jpg/500px-Basmati_Rice_India%2C_raw.jpg",
  "Masala Potato Chips": "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/Potato_chips_2.jpg/500px-Potato_chips_2.jpg",
  "Choco Wafer Rolls": "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c7/Chocolate_Crispy_Wafer_%2810939378225%29.jpg/500px-Chocolate_Crispy_Wafer_%2810939378225%29.jpg",
  "Moisturizing Face Cream": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6e/Moisturizing_cream.jpg/500px-Moisturizing_cream.jpg",
  "Ball Pen Pack": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4d/Ballpoint_Pen.jpg/500px-Ballpoint_Pen.jpg",
  "Gel Pen Set": "https://upload.wikimedia.org/wikipedia/commons/1/17/A_bunch_of_gel_pens.jpg",
  "Aloe Face Wash": "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Aloe_vera_gel_%2820241107%29.jpg/500px-Aloe_vera_gel_%2820241107%29.jpg",
  "Bhujia Namkeen": "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Bikaneri_bhujia_in_West_Bengal%2C_India%2C_photographed_by_Yogabrata_Chakraborty%2C_on_March_11%2C_2023.jpg/500px-Bikaneri_bhujia_in_West_Bengal%2C_India%2C_photographed_by_Yogabrata_Chakraborty%2C_on_March_11%2C_2023.jpg",
};

const products = [
  {
    name: 'Wireless Mouse',
    description: 'Ergonomic wireless mouse with adjustable DPI and silent clicks. Perfect for office and home use with a comfortable grip and long battery life.',
    price: 799.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Wireless_mouse_block.jpg/500px-Wireless_mouse_block.jpg',
    category: 'Accessories',
    stock: 50,
  },
  {
    name: 'Mechanical Keyboard',
    description: 'RGB backlit mechanical keyboard with blue switches. Full-size layout with Numpad, anti-ghosting, and durable construction for typing and gaming.',
    price: 1499.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Mechanical_keyboard_example.jpg/500px-Mechanical_keyboard_example.jpg',
    category: 'Accessories',
    stock: 35,
  },
  {
    name: 'USB-C Hub Adapter',
    description: '7-in-1 USB-C hub with HDMI, USB 3.0 ports, SD card reader, and PD charging. Compatible with laptops, tablets, and phones.',
    price: 1299.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ce/USB_OTG_Type-C_Adapter_-_A.jpg/500px-USB_OTG_Type-C_Adapter_-_A.jpg',
    category: 'Electronics',
    stock: 40,
  },
  {
    name: 'Noise Cancelling Headphones',
    description: 'Over-ear wireless headphones with active noise cancellation, 30-hour battery, and premium sound quality. Foldable design for portability.',
    price: 3499.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0a/Bose_QuietComfort_25_Acoustic_Noise_Cancelling_Headphones_with_Carry_Case.jpg/500px-Bose_QuietComfort_25_Acoustic_Noise_Cancelling_Headphones_with_Carry_Case.jpg',
    category: 'Electronics',
    stock: 25,
  },
  {
    name: 'Desk Lamp',
    description: 'LED desk lamp with adjustable brightness and color temperature. Touch controls, USB charging port, and modern minimalist design.',
    price: 1199.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/A_desk_lamp.jpg/500px-A_desk_lamp.jpg',
    category: 'Home',
    stock: 30,
  },
  {
    name: 'Webcam HD 1080p',
    description: 'Full HD 1080p webcam with built-in microphone and auto-focus. Ideal for video calls, streaming, and online meetings.',
    price: 2499.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e5/Logitech_Brio_301_webcam_HS3.jpg/500px-Logitech_Brio_301_webcam_HS3.jpg',
    category: 'Electronics',
    stock: 20,
  },
  {
    name: 'Monitor Stand Riser',
    description: 'Adjustable aluminum monitor stand riser with storage drawer. Improves ergonomics and adds extra desk space. Supports up to 32 inch monitors.',
    price: 1899.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/42/Laptop_and_monitor_on_a_stands.jpg/500px-Laptop_and_monitor_on_a_stands.jpg',
    category: 'Office',
    stock: 15,
  },
  {
    name: 'Portable Charger 20000mAh',
    description: 'High-capacity 20000mAh power bank with dual USB ports and fast charging support. LED indicator and compact design for travel.',
    price: 1599.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/75/Portable_power_bank.jpg/500px-Portable_power_bank.jpg',
    category: 'Electronics',
    stock: 45,
  },
  {
    name: 'Ergonomic Office Chair',
    description: 'Adjustable ergonomic office chair with lumbar support, armrests, and breathable mesh back. Height-adjustable with smooth-rolling casters.',
    price: 8999.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8a/Prototype_ergonomic_office_chair%2C_V%26A_London.jpg/500px-Prototype_ergonomic_office_chair%2C_V%26A_London.jpg',
    category: 'Office',
    stock: 10,
  },
  {
    name: 'Plant Pot Set',
    description: 'Set of 3 ceramic plant pots in modern pastel colors with bamboo trays. Perfect for succulents and indoor plants. drainage holes included.',
    price: 699.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/68/Copped_Hall_kitchen_walled_garden%2C_plant_pot_stack%2C_Essex%2C_England.jpg/500px-Copped_Hall_kitchen_walled_garden%2C_plant_pot_stack%2C_Essex%2C_England.jpg',
    category: 'Home',
    stock: 60,
  },
  {
    name: 'Notebook Journal',
    description: 'Premium hardcover notebook with 200 lined pages, lay-flat binding, and expandable pocket. Ribbon bookmark and elastic closure.',
    price: 399.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Notebook_writing.jpg/500px-Notebook_writing.jpg',
    category: 'Office',
    stock: 80,
  },
  {
    name: 'Bluetooth Speaker',
    description: 'Compact portable Bluetooth speaker with 360-degree sound, IPX7 waterproof rating, and 12-hour battery. Great for outdoor use.',
    price: 2199.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/JBL_Flip_3_bluetooth_speaker_%28DSCF2653%29.jpg/500px-JBL_Flip_3_bluetooth_speaker_%28DSCF2653%29.jpg',
    category: 'Electronics',
    stock: 30,
  },
  {
    name: 'Fresh Bananas',
    description: 'Naturally sweet, ripe bananas selected for everyday snacking and breakfast bowls.',
    price: 48.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/c4/Abundant_Fresh_Bananas_Displayed.jpg/500px-Abundant_Fresh_Bananas_Displayed.jpg',
    category: 'Fresh Produce',
    stock: 80,
  },
  {
    name: 'Farm Fresh Apples',
    description: 'Crisp red apples with a refreshing bite, perfect for lunch boxes and quick snacks.',
    price: 149.00,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/d/d4/Farm-Fresh_apple.png',
    category: 'Fresh Produce',
    stock: 60,
  },
  {
    name: 'Baby Spinach',
    description: 'Tender green spinach leaves, washed and ready for salads, smoothies, and cooking.',
    price: 65.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/46/RECALLED-Baby_spinach_%2820800465983%29.jpg/500px-RECALLED-Baby_spinach_%2820800465983%29.jpg',
    category: 'Fresh Produce',
    stock: 45,
  },
  {
    name: 'Full Cream Milk',
    description: 'Rich and creamy daily milk for tea, coffee, cereal, and wholesome family moments.',
    price: 68.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/30/Milk_bottle_and_two_doughnuts.jpg/500px-Milk_bottle_and_two_doughnuts.jpg',
    category: 'Dairy & Eggs',
    stock: 75,
  },
  {
    name: 'Farm Eggs 12 Pack',
    description: 'Fresh protein-rich eggs packed carefully for breakfast, baking, and everyday cooking.',
    price: 112.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4c/Egg_cartons_with_chicken_eggs_02.jpg/500px-Egg_cartons_with_chicken_eggs_02.jpg',
    category: 'Dairy & Eggs',
    stock: 52,
  },
  {
    name: 'Salted Potato Chips',
    description: 'Golden, crunchy potato chips with just the right amount of salt for sharing.',
    price: 35.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/63/Zapp%27s_Potato_Chips_-_Salt_%26_Vinegar.jpg/500px-Zapp%27s_Potato_Chips_-_Salt_%26_Vinegar.jpg',
    category: 'Snacks',
    stock: 90,
  },
  {
    name: 'Chocolate Chip Cookies',
    description: 'Buttery cookies loaded with chocolate chips for a sweet afternoon pick-me-up.',
    price: 89.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/41/6cookies.JPG/500px-6cookies.JPG',
    category: 'Snacks',
    stock: 65,
  },
  {
    name: 'Sparkling Lime Soda',
    description: 'Bright, fizzy lime refreshment served chilled or poured over ice.',
    price: 55.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Nimbu_Soda_Or_Lemon_Soda.jpg/500px-Nimbu_Soda_Or_Lemon_Soda.jpg',
    category: 'Beverages',
    stock: 70,
  },
  {
    name: 'Cold Brew Coffee',
    description: 'Smooth slow-steeped coffee with a rich finish for your focused mornings.',
    price: 155.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2a/Irish_Cream_Cold_Brew_at_Starbucks_-_2021-11-15_-_Sarah_Stierch.jpg/500px-Irish_Cream_Cold_Brew_at_Starbucks_-_2021-11-15_-_Sarah_Stierch.jpg',
    category: 'Beverages',
    stock: 40,
  },
  {
    name: 'Gentle Dish Wash',
    description: 'Powerful grease-cutting dish wash with a fresh citrus scent and gentle formula.',
    price: 129.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Dish-soap.jpg/500px-Dish-soap.jpg',
    category: 'Home Care',
    stock: 55,
  },
  {
    name: 'Laundry Liquid Fresh',
    description: 'Concentrated laundry liquid that lifts everyday stains while keeping colours bright.',
    price: 289.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/HK_SKD_TKO_Po_Yap_Road_%E5%B0%87%E8%BB%8D%E6%BE%B3%E5%BB%A3%E5%A0%B4_Tseung_Kwan_O_Plaza_K-mart_fresh_food_indoor_market_shop_Kai_Bo_Food_Supermarket_Wayway_Laundry_Liquid_plastic_bottle_July_2021_SS2_01.jpg/500px-thumbnail.jpg',
    category: 'Home Care',
    stock: 35,
  },
  {
    name: 'Aloe Face Wash',
    description: 'A refreshing aloe face wash that gently cleanses without drying your skin.',
    price: 199.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4f/Aloe_vera_gel_%2820241107%29.jpg/500px-Aloe_vera_gel_%2820241107%29.jpg',
    category: 'Personal Care',
    stock: 48,
  },
  {
    name: 'Daily Shampoo',
    description: 'Lightweight everyday shampoo for clean, soft hair with a fresh botanical scent.',
    price: 249.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/df/Dove_shampoo_bottle_in_black_background.jpg/500px-Dove_shampoo_bottle_in_black_background.jpg',
    category: 'Personal Care',
    stock: 42,
  },
  {
    name: 'Basmati Rice 5kg',
    description: 'Long-grain aromatic basmati rice for fluffy biryanis, pulao, and everyday meals.',
    price: 589.00,
    imageUrl: 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f8/Basmati_Rice_India%2C_raw.jpg/500px-Basmati_Rice_India%2C_raw.jpg',
    category: 'Pantry',
    stock: 30,
  },
  {
    name: 'Classic Wheat Flour',
    description: 'Finely milled whole wheat flour for soft rotis, parathas, and homemade bakes.',
    price: 299.00,
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/1/11/Wheat-flour.jpg',
    category: 'Pantry',
    stock: 38,
  },
];

const groceryCatalog = {
  'Fresh Produce': [
    'Fresh Oranges', 'Alphonso Mangoes', 'Green Grapes', 'Pomegranate', 'Papaya',
    'Watermelon', 'Pineapple', 'Avocado', 'Baby Potatoes', 'Red Onions',
    'Tomatoes', 'Green Capsicum', 'Broccoli', 'Cauliflower', 'Cucumber',
    'Carrots', 'Coriander', 'Mint Leaves', 'Sweet Corn', 'Lemons',
  ],
  'Dairy & Eggs': [
    'Toned Milk', 'Low Fat Milk', 'Paneer Fresh', 'Salted Butter', 'Unsalted Butter',
    'Cheddar Cheese', 'Mozzarella Cheese', 'Greek Yogurt', 'Plain Curd', 'Strawberry Yogurt',
    'Buttermilk', 'Fresh Cream', 'Coconut Milk', 'Almond Milk', 'Chocolate Milk',
    'Brown Eggs', 'Quail Eggs', 'Cheese Slices', 'Cottage Cheese', 'Vanilla Yogurt',
  ],
  Snacks: [
    'Masala Potato Chips', 'Classic Nachos', 'Cheese Puffs', 'Roasted Peanuts', 'Salted Cashews',
    'Trail Mix', 'Granola Bars', 'Oat Cookies', 'Cream Biscuits', 'Butter Crackers',
    'Kettle Corn', 'Roasted Makhana', 'Banana Chips', 'Bhujia Namkeen', 'Choco Wafer Rolls',
    'Peanut Chikki', 'Protein Bar', 'Rice Cakes', 'Popcorn Butter', 'Fruit Gummies',
  ],
  Beverages: [
    'Mango Juice', 'Orange Juice', 'Apple Juice', 'Coconut Water', 'Mineral Water',
    'Green Tea', 'Masala Tea', 'Instant Coffee', 'Iced Tea Peach', 'Cola Classic',
    'Ginger Ale', 'Tonic Water', 'Energy Drink', 'Sports Drink', 'Lemonade',
    'Berry Smoothie', 'Mango Lassi', 'Vanilla Milkshake', 'Hot Chocolate', 'Herbal Infusion',
  ],
  'Home Care': [
    'Floor Cleaner Lemon', 'Glass Cleaner', 'Bathroom Cleaner', 'Toilet Cleaner', 'Kitchen Degreaser',
    'Disinfectant Spray', 'Multi Surface Cleaner', 'Fabric Softener', 'Washing Powder', 'Dishwasher Tablets',
    'Sponge Scrubbers', 'Microfiber Cloths', 'Garbage Bags', 'Kitchen Towels', 'Air Freshener',
    'Mosquito Repellent', 'Toilet Freshener', 'Drain Opener', 'Rubber Gloves', 'Storage Bags',
  ],
  'Personal Care': [
    'Moisturizing Face Cream', 'Vitamin C Serum', 'Sunscreen SPF 50', 'Lip Balm', 'Body Lotion',
    'Hand Wash', 'Body Wash', 'Conditioner', 'Hair Oil', 'Toothpaste Fresh Mint',
    'Toothbrush Soft', 'Mouthwash', 'Deodorant Roll On', 'Bath Soap', 'Hand Cream',
    'Face Scrub', 'Cotton Buds', 'Tissue Box', 'Wet Wipes', 'Shaving Foam',
  ],
  Pantry: [
    'Toor Dal', 'Moong Dal', 'Chana Dal', 'Rajma Red', 'Kabuli Chana',
    'Poha Thick', 'Oats Rolled', 'Quinoa', 'Brown Rice', 'Sugar Fine',
    'Rock Salt', 'Black Pepper', 'Turmeric Powder', 'Red Chilli Powder', 'Garam Masala',
    'Refined Sunflower Oil', 'Extra Virgin Olive Oil', 'Peanut Butter', 'Tomato Ketchup', 'Mixed Pickle',
  ],
  Accessories: [
    'Laptop Sleeve', 'Wireless Mouse Pad', 'USB-C Cable', 'HDMI Cable', 'Phone Stand',
    'Laptop Stand', 'Cable Organizer', 'Wireless Presenter', 'Keyboard Wrist Rest', 'Desk Mat',
    'Webcam Cover', 'Screen Cleaning Kit', 'Bluetooth Adapter', 'USB Flash Drive', 'Card Reader',
    'Phone Grip', 'Tablet Sleeve', 'Travel Adapter', 'Charging Dock', 'Smart Tag',
  ],
  Electronics: [
    'Smart LED Bulb', 'Wi-Fi Router', 'Smart Plug', 'Fitness Band', 'Smart Watch',
    'Mini Projector', 'Wireless Earbuds', 'Soundbar', 'E-Reader', 'Action Camera',
    'Tripod Stand', 'Electric Kettle', 'Air Purifier', 'Robot Vacuum', 'Digital Weighing Scale',
    'Power Strip', 'LED Strip Lights', 'Table Fan', 'Electric Toothbrush', 'Phone Gimbal',
  ],
  Home: [
    'Cotton Cushion Set', 'Ceramic Dinner Set', 'Glass Tumbler Set', 'Wooden Serving Tray', 'Bath Towel',
    'Hand Towel Set', 'Scented Candle', 'Decorative Vase', 'Bamboo Basket', 'Storage Organizer',
    'Bedside Lamp', 'Wall Clock', 'Photo Frame', 'Coaster Set', 'Kitchen Apron',
    'Water Bottle', 'Lunch Box', 'Curtain Set', 'Door Mat', 'Laundry Basket',
  ],
  Office: [
    'Ball Pen Pack', 'Gel Pen Set', 'Highlighter Set', 'Sticky Notes', 'A4 Notebook',
    'Drawing Pencils', 'Whiteboard Marker', 'Stapler Kit', 'Paper Clips', 'File Folder Set',
    'Envelope Pack', 'Correction Tape', 'Desk Calendar', 'Scissors', 'Glue Stick',
    'Ruler Set', 'Sketchbook', 'Binder Clips', 'Index Cards', 'Clipboard',
  ],
};

const generatedProducts = Object.entries(groceryCatalog).flatMap(([category, names]) =>
  names.map((name, index) => ({
    name,
    description: `${name} selected for easy everyday shopping, reliable quality, and a happier home pantry.`,
    price: Number((49 + ((index * 37) % 451) + (category.length % 5) * 10).toFixed(2)),
    imageUrl: imageMap[name],
    category,
    stock: 18 + ((index * 11) % 64),
  }))
);

async function main() {
  console.log('Seeding database...');

  await prisma.cartItem.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.cart.deleteMany();
  await prisma.product.deleteMany();

  for (const product of [...products, ...generatedProducts]) {
    await prisma.product.create({ data: product });
  }

  const count = await prisma.product.count();
  console.log(`Seeded ${count} products successfully.`);
}

main()
  .catch((e) => {
    console.error('Seed error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
